version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
    
    env_file:
      - devcontainer.env
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  # https://saltares.com/improve-your-nextauthjs-app-local-development-experience-with-a-dockerized-smtp-server/
  mailhog:
    image: mailhog/mailhog

volumes:
  postgres-data:
