name: Publish to Docker
on:
  push:
    branches:
      - main
permissions:
  packages: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Add your test steps here if needed...
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/KKKIIO/vocab-card/vocab-card
            ghcr.io/KKKIIO/vocab-card/vocab-card-migrate
          tags: type=sha
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build app image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
      - name: Build migrate image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: migrate.Dockerfile
          tags: ${{ fromJSON(steps.meta.outputs.json).tags[1] }}
